In [1]:
import pandas as pd
import numpy as np

In [2]:
position_war = pd.read_csv('2015_2022_position_war.csv')
position_war

,Name,Team,G,PA,HR,R,RBI,SB,BB%,K%,...,OBP,SLG,wOBA,xwOBA,wRC+,BsR,Off,Def,WAR,playerid
0,Mike Trout,LAA,914,3964,252,679,589,102,16.4%,21.8%,...,0.425,0.609,0.427,NaN,176.0,31.3,394.0,-9.3,52.9,10155
1,Mookie Betts,- - -,1061,4851,208,836,631,151,10.2%,13.6%,...,0.368,0.523,0.377,NaN,136.0,46.8,261.4,48.0,48.3,13611
2,Francisco Lindor,- - -,1063,4740,184,679,581,125,8.5%,15.3%,...,0.342,0.474,0.346,NaN,118.0,6.8,110.8,138.8,42.0,12916
3,Nolan Arenado,- - -,1140,4850,271,696,855,19,8.6%,14.9%,...,0.353,0.553,0.376,NaN,127.0,-1.6,157.6,90.6,41.3,9777
4,Jose Altuve,HOU,1064,4707,171,731,536,148,8.4%,12.7%,...,0.373,0.500,0.372,NaN,140.0,1.4,224.7,15.6,40.7,5417
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3256,Alexi Amarista,- - -,279,683,6,59,60,15,5.7%,17.4%,...,0.268,0.301,0.247,NaN,48.0,-0.9,-43.6,-4.5,-2.7,9063
3257,JB Shuck,- - -,257,605,4,56,35,13,7.6%,11.4%,...,0.283,0.292,0.257,NaN,59.0,0.2,-29.9,-16.5,-2.7,6677
3258,Drew Butera,- - -,305,740,11,69,68,0,6.4%,24.7%,...,0.264,0.312,0.254,NaN,51.0,-1.1,-45.5,-6.7,-2.7,3411
3259,Lewis Brinson,- - -,357,1150,28,91,109,10,5.0%,28.4%,...,0.246,0.328,0.249,NaN,55.0,1.1,-65.0,-6.4,-3.5,14352
3260,Victor Martinez,DET,514,2038,57,174,251,0,7.3%,12.5%,...,0.320,0.397,0.308,NaN,91.0,-28.0,-50.5,-54.3,-3.8,393

In [3]:
pitcher_war = pd.read_csv('2015_2022_pitcher_war.csv')
pitcher_war

,Name,Team,W,L,SV,G,GS,IP,K/9,BB/9,...,LOB%,GB%,HR/FB,vFA (pi),ERA,xERA,FIP,xFIP,WAR,playerid
0,Max Scherzer,- - -,110,52,0,223,223,1442.2,11.68,1.95,...,81.1%,34.9%,10.8%,94.6,2.71,NaN,2.85,3.15,44.1,3137
1,Jacob deGrom,NYM,73,51,0,187,187,1185.2,11.11,1.97,...,79.7%,44.7%,11.3%,96.6,2.50,NaN,2.61,2.81,37.6,10954
2,Clayton Kershaw,LAD,99,38,0,190,189,1202.2,10.19,1.53,...,80.2%,48.7%,13.2%,92.3,2.48,NaN,2.79,2.78,34.8,2036
3,Gerrit Cole,- - -,109,59,0,226,226,1394.2,10.92,2.29,...,77.0%,42.9%,13.2%,96.9,3.19,NaN,3.14,3.13,34.2,13125
4,Justin Verlander,- - -,92,44,0,184,184,1185.0,10.39,2.05,...,80.9%,34.1%,10.9%,94.7,2.76,NaN,3.24,3.56,31.7,8700
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2065,Edgar Garcia,- - -,2,1,1,52,0,57.0,9.16,6.00,...,65.0%,36.4%,24.7%,93.8,7.74,NaN,7.32,5.70,-1.5,19276
2066,David Hess,- - -,6,22,0,62,34,210.1,6.89,3.42,...,67.4%,32.6%,18.9%,92.6,6.25,NaN,6.72,5.70,-1.6,16130
2067,David Holmberg,- - -,3,8,0,43,13,86.0,5.02,5.23,...,76.1%,42.0%,18.3%,88.3,5.65,NaN,7.38,6.39,-1.7,7725
2068,Chris Beck,- - -,4,4,1,103,1,130.0,5.95,5.19,...,73.9%,43.1%,17.6%,95.1,5.88,NaN,6.42,5.74,-1.8,13418
2069,Josh Osich,- - -,13,6,1,251,1,220.2,8.12,3.51,...,70.2%,49.5%,21.0%,95.4,5.02,NaN,5.30,4.38,-2.4,11528

In [8]:
position_minors = pd.read_csv("position_minors.csv")
position_major = pd.read_csv("position_majors.csv")

In [20]:
df = pd.concat([position_minors, position_major]).sort_values(by=['name', 'gameDate'])
df

,name,gameDate,gameID,team,opponent,league,hits,atBats,homeRuns,runs,rbi,stolenBases,strikeOuts,walks,avg,obp,slg,ops
4021,AJ Pollock,2013-04-01,346191,Arizona Diamondbacks,St. Louis Cardinals,National League,3,4,0,0,2,0,1,0,0.750,0.750,1.000,1.750
4022,AJ Pollock,2013-04-02,346757,Arizona Diamondbacks,St. Louis Cardinals,National League,0,2,0,0,0,0,0,0,0.500,0.500,0.667,1.167
4023,AJ Pollock,2013-04-03,346772,Arizona Diamondbacks,St. Louis Cardinals,National League,0,3,0,0,0,0,1,0,0.333,0.333,0.444,0.777
4024,AJ Pollock,2013-04-05,346802,Arizona Diamondbacks,Milwaukee Brewers,National League,0,3,0,0,0,0,0,0,0.250,0.250,0.333,0.583
4025,AJ Pollock,2013-04-06,346805,Arizona Diamondbacks,Milwaukee Brewers,National League,0,1,0,0,0,0,0,0,0.231,0.231,0.308,0.539
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
170724,Zack Short,2022-09-24,702621,Toledo Mud Hens,Columbus Clippers,International League,0,4,0,0,0,0,2,0,0.230,0.356,0.378,0.734
170725,Zack Short,2022-09-25,702616,Toledo Mud Hens,Columbus Clippers,International League,1,5,0,0,1,0,1,0,0.229,0.354,0.376,0.730
170726,Zack Short,2022-09-26,702628,Toledo Mud Hens,Iowa Cubs,International League,1,3,0,1,0,0,0,2,0.230,0.356,0.376,0.732
170727,Zack Short,2022-09-27,702627,Toledo Mud Hens,Iowa Cubs,International League,1,3,0,2,1,0,0,0,0.231,0.357,0.376,0.733
170728,Zack Short,2022-09-28,702622,Toledo Mud Hens,Iowa Cubs,International League,0,4,0,0,0,0,3,0,0.229,0.355,0.373,0.728

In [33]:
df["gameDate"] = pd.to_datetime(df["gameDate"])
df['season'] = pd.DatetimeIndex(df['gameDate']).year
df["days_between_game"] = df.groupby(["name", "season"])["gameDate"].transform(lambda X: X.diff())
df["days_between_game"] = df["days_between_game"].apply(lambda x: x.days)
df.reset_index(inplace=True)

In [45]:
df[(df["name"] == "Brandon Nimmo") & (df["season"] == 2018)].sort_values("gameDate")[100:]
def is_callup(X):
    print(X)
    if (X["days_between_game"] > 7) & (df[X.index - 1]["league"] != X.league):
        return 1
    else:
        return 0
# df.transform(is_callup, axis=1)

index                                4021
name                           AJ Pollock
gameDate              2013-04-01 00:00:00
gameID                             346191
team                 Arizona Diamondbacks
opponent              St. Louis Cardinals
league                    National League
hits                                    3
atBats                                  4
homeRuns                                0
runs                                    0
rbi                                     2
stolenBases                             0
strikeOuts                              1
walks                                   0
avg                                  0.75
obp                                  0.75
slg                                   1.0
ops                                  1.75
season                               2013
days_between_game                     NaN
Name: 0, dtype: object
                                 0                     1       \
index                              4021                  4022
name                         AJ Pollock            AJ Pollock
gameDate            2013-04-01 00:00:00   2013-04-02 00:00:00
gameID                           346191                346757
team               Arizona Diamondbacks  Arizona Diamondbacks
opponent            St. Louis Cardinals   St. Louis Cardinals
league                  National League       National League
hits                                  3                     0
atBats                                4                     2
homeRuns                              0                     0
runs                                  0                     0
rbi                                   2                     0
stolenBases                           0                     0
strikeOuts                            1                     0
walks                                 0                     0
avg                                0.75                   0.5
obp                                0.75                   0.5
slg                                 1.0                 0.667
ops                                1.75                 1.167
season                             2013                  2013
days_between_game                   NaN                   1.0

                                 2                     3       \
index                              4023                  4024
name                         AJ Pollock            AJ Pollock
gameDate            2013-04-03 00:00:00   2013-04-05 00:00:00
gameID                           346772                346802
team               Arizona Diamondbacks  Arizona Diamondbacks
opponent            St. Louis Cardinals     Milwaukee Brewers
league                  National League       National League
hits                                  0                     0
atBats                                3                     3
homeRuns                              0                     0
runs                                  0                     0
rbi                                   0                     0
stolenBases                           0                     0
strikeOuts                            1                     0
walks                                 0                     0
avg                               0.333                  0.25
obp                               0.333                  0.25
slg                               0.444                 0.333
ops                               0.777                 0.583
season                             2013                  2013
days_between_game                   1.0                   2.0

                                 4                     5       \
index                              4025                  4026
name                         AJ Pollock            AJ Pollock
gameDate            2013-04-06 00:00:00   2013-04-08 00:00:00
gameID                           346805                346839
team               Arizona Diamondbacks  Arizona Diamondbacks
opponent              Milwaukee Brewers    Pittsburgh Pirates
league                  National League       National League
hits                                  0                     0
atBats                                1                     4
homeRuns                              0                     0
runs                                  0                     0
rbi                                   0                     0
stolenBases                           0                     0
strikeOuts                            0                     1
walks                                 0                     0
avg                               0.231                 0.176
obp                               0.231                 0.176
slg                               0.308                 0.235
ops                               0.539                 0.411
season                             2013                  2013
days_between_game                   1.0                   2.0

                                 6                     7       \
index                              4027                  4028
name                         AJ Pollock            AJ Pollock
gameDate            2013-04-10 00:00:00   2013-04-12 00:00:00
gameID                           346867                346889
team               Arizona Diamondbacks  Arizona Diamondbacks
opponent             Pittsburgh Pirates   Los Angeles Dodgers
league                  National League       National League
hits                                  3                     1
atBats                                5                     4
homeRuns                              2                     0
runs                                  3                     1
rbi                                   4                     0
stolenBases                           1                     0
strikeOuts                            2                     0
walks                                 0                     0
avg                               0.273                 0.269
obp                               0.273                 0.269
slg                               0.636                 0.577
ops                               0.909                 0.846
season                             2013                  2013
days_between_game                   2.0                   2.0

                                 8                     9       ...  \
index                              4029                  4030  ...
name                         AJ Pollock            AJ Pollock  ...
gameDate            2013-04-13 00:00:00   2013-04-14 00:00:00  ...
gameID                           346904                346919  ...
team               Arizona Diamondbacks  Arizona Diamondbacks  ...
opponent            Los Angeles Dodgers   Los Angeles Dodgers  ...
league                  National League       National League  ...
hits                                  1                     1  ...
atBats                                3                     3  ...
homeRuns                              0                     0  ...
runs                                  0                     1  ...
rbi                                   1                     0  ...
stolenBases                           0                     0  ...
strikeOuts                            1                     0  ...
walks                                 0                     0  ...
avg                               0.276                 0.281  ...
obp                               0.276                 0.281  ...
slg                               0.586                 0.594  ...
ops                               0.862                 0.875  ...
season                             2013                  2013  ...
days_between_game                   1.0                   1.0  ...

                                 355006                355007  \
index                            170719                170720
name                         Zack Short            Zack Short
gameDate            2022-09-20 00:00:00   2022-09-21 00:00:00
gameID                           664408                664407
team                    Toledo Mud Hens       Toledo Mud Hens
opponent              Columbus Clippers     Columbus Clippers
league             International League  International League
hits                                  3                     0
atBats                                5                     4
homeRuns                              0                     0
runs                                  1                     0
rbi                                   1                     0
stolenBases                           0                     0
strikeOuts                            2                     2
walks                                 1                     0
avg                               0.231                 0.229
obp                               0.356                 0.353
slg                               0.386                 0.382
ops                               0.742                 0.735
season                             2022                  2022
days_between_game                   2.0                   1.0

                                 355008                355009  \
index                            170721                170722
name                         Zack Short            Zack Short
gameDate            2022-09-22 00:00:00   2022-09-22 00:00:00
gameID                           664538                666167
team                    Toledo Mud Hens       Toledo Mud Hens
opponent              Columbus Clippers     Columbus Clippers
league             International League  International League
hits                                  1                     2
atBats                                3                     3
homeRuns                              0                     0
runs                                  1                     1
rbi                                   0                     1
stolenBases                           0                     0
strikeOuts                            1                     1
walks                                 1                     1
avg                                0.23                 0.233
obp                               0.354                 0.357
slg                               0.382                 0.384
ops                               0.736                 0.741
season                             2022                  2022
days_between_game                   1.0                   0.0

                                 355010                355011  \
index                            170723                170724
name                         Zack Short            Zack Short
gameDate            2022-09-23 00:00:00   2022-09-24 00:00:00
gameID                           702617                702621
team                    Toledo Mud Hens       Toledo Mud Hens
opponent              Columbus Clippers     Columbus Clippers
league             International League  International League
hits                                  0                     0
atBats                                2                     4
homeRuns                              0                     0
runs                                  0                     0
rbi                                   1                     0
stolenBases                           0                     0
strikeOuts                            2                     2
walks                                 2                     0
avg                               0.232                  0.23
obp                               0.358                 0.356
slg                               0.382                 0.378
ops                                0.74                 0.734
season                             2022                  2022
days_between_game                   1.0                   1.0

                                 355012                355013  \
index                            170725                170726
name                         Zack Short            Zack Short
gameDate            2022-09-25 00:00:00   2022-09-26 00:00:00
gameID                           702616                702628
team                    Toledo Mud Hens       Toledo Mud Hens
opponent              Columbus Clippers             Iowa Cubs
league             International League  International League
hits                                  1                     1
atBats                                5                     3
homeRuns                              0                     0
runs                                  0                     1
rbi                                   1                     0
stolenBases                           0                     0
strikeOuts                            1                     0
walks                                 0                     2
avg                               0.229                  0.23
obp                               0.354                 0.356
slg                               0.376                 0.376
ops                                0.73                 0.732
season                             2022                  2022
days_between_game                   1.0                   1.0

                                 355014                355015
index                            170727                170728
name                         Zack Short            Zack Short
gameDate            2022-09-27 00:00:00   2022-09-28 00:00:00
gameID                           702627                702622
team                    Toledo Mud Hens       Toledo Mud Hens
opponent                      Iowa Cubs             Iowa Cubs
league             International League  International League
hits                                  1                     0
atBats                                3                     4
homeRuns                              0                     0
runs                                  2                     0
rbi                                   1                     0
stolenBases                           0                     0
strikeOuts                            0                     3
walks                                 0                     0
avg                               0.231                 0.229
obp                               0.357                 0.355
slg                               0.376                 0.373
ops                               0.733                 0.728
season                             2022                  2022
days_between_game                   1.0                   1.0

[21 rows x 355016 columns]

ValueError: Transform function failed

In [47]:
df.sort_values("days_between_game", ascending=False)[~df["league"].isin(["National League", "American League"])]

C:\Users\brill\AppData\Local\Temp/ipykernel_32804/1177599148.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df.sort_values("days_between_game", ascending=False)[~df["league"].isin(["National League", "American League"])]

,index,name,gameDate,gameID,team,opponent,league,hits,atBats,homeRuns,...,rbi,stolenBases,strikeOuts,walks,avg,obp,slg,ops,season,days_between_game
30880,13417,Avisail Garcia,2014-08-01,390853,Charlotte Knights,Durham Bulls,International League,2,4,0,...,0,0,2,0,0.500,0.500,0.500,1.000,2014,114.0
103303,47644,Esteban Quiroz,2018-08-10,551358,GCL Red Sox,GCL Twins,Gulf Coast League,2,3,0,...,3,0,0,0,0.667,0.667,1.333,2.000,2018,109.0
37767,16288,Brandon Dixon,2022-08-11,710248,ACL Padres,ACL White Sox,Arizona Complex League,2,3,0,...,0,0,0,0,0.667,0.667,0.667,1.334,2022,106.0
291631,138499,Ronald Acuna Jr.,2016-08-22,472308,GCL Braves,GCL Blue Jays,Gulf Coast League,1,3,0,...,1,0,0,0,0.333,0.500,0.333,0.833,2016,105.0
320898,154230,Travis d'Arnaud,2013-07-24,367378,GCL Mets,GCL Marlins,Gulf Coast League,1,3,0,...,0,0,0,0,0.333,0.333,0.333,0.666,2013,98.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
354404,170184,Zack Short,2016-06-28,470730,AZL Cubs,AZL Giants,Arizona League,1,1,0,...,0,0,0,3,1.000,1.000,1.000,2.000,2016,NaN
354457,170237,Zack Short,2017-04-07,500225,South Bend Cubs,West Michigan Whitecaps,Midwest League,0,3,0,...,0,0,2,0,0.000,0.000,0.000,0.000,2017,NaN
354588,170368,Zack Short,2018-04-05,544884,Tennessee Smokies,Mississippi Braves,Southern League,0,4,0,...,0,0,2,1,0.000,0.200,0.000,0.200,2018,NaN
354712,170492,Zack Short,2019-04-04,579767,Iowa Cubs,Nashville Sounds,Pacific Coast League,1,3,0,...,0,0,0,0,0.333,0.500,0.333,0.833,2019,NaN
354882,170601,Zack Short,2022-04-05,664476,Toledo Mud Hens,Rochester Red Wings,International League,0,4,0,...,0,0,3,0,0.000,0.000,0.000,0.000,2022,NaN